name: task2_env
channels:
  - pytorch
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - cudatoolkit=11.1.1
  - matplotlib=3.4.2
  - numpy=1.19.5
  - pandas=1.2.5
  - pillow=8.2.0
  - python=3.8.10
  - pytorch=1.9.0
  - torchvision=0.10.0
  - tqdm

